name:                HasBigDecimal
version:             0.2.0.0
github:              "thma/HasBigDecimal"
license:             Apache-2.0
author:              "Thomas Mahler"
maintainer:          "thma@apache.org"
copyright:           "2018-2022 Thomas Mahler"
synopsis:            "A library for arbitrary precision decimal numbers."
tested-with:         GHC == 8.10.7
                   , GHC == 9.0.2
                   , GHC == 9.2.1

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/thma/HasBigDecimal#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  HasBigDecimal-Demo:
    main:                Main.hs
    source-dirs:         demo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HasBigDecimal

  benchmark:
    main:                Main.hs
    source-dirs:         benchmark
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HasBigDecimal
      - criterion    

tests:
  HasBigDecimal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HasBigDecimal
    - hspec
    - QuickCheck
    verbatim:
      build-tool-depends:
        hspec-discover:hspec-discover == 2.*

      